#!/bin/bash
# (l)ist (c)ontents of file/dir/misc types and total size in the current
# directory.
# 
#   Copyright (c) 2014-2016, Matt Busby @MrMattBusby.
#   All rights reserved.
#
#   Redistribution and use in source and binary forms, with or without
#   modification, are permitted provided that the following conditions
#   are met:
#   
#   1. Redistributions of source code must retain the above copyright
#      notice, this list of conditions and the following disclaimer.
#   
#   2. Redistributions in binary form must reproduce the above copyright
#      notice, this list of conditions and the following disclaimer in
#      the documentation and/or other materials provided with the
#      distribution.
#   
#   3. Neither the name of the copyright holder nor the names of its
#      contributors may be used to endorse or promote products derived
#      from this software without specific prior written permission.
#   
#   THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
#   "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
#   LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
#   FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
#   COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
#   INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
#   BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
#   LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
#   CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
#   LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY
#   WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
#   POSSIBILITY OF SUCH DAMAGE.

if [ $# -eq 0 ] ; then
  pushd . 1> /dev/null
else
  pushd $@ 1> /dev/null
fi
DIR=$(pwd -P $@)
echo -e "${CMDCOL}>>> Listing contents of \"$DIR\" (ignoring items with permissions):${NC}"
echo
echo -e "${CMDCOL}All   :${NC} $(find . -maxdepth 1 -regex '\.\/.*' 2>/dev/null|wc -l) ($(find . -maxdepth 1 \
  -regex '\.\/\..*' 2>/dev/null|wc -l) hidden)"
echo -e "${CMDCOL}Dirs  :${NC} $(find . -maxdepth 1 -type d -regex '\.\/.*' 2>/dev/null|wc -l) ($(find . -maxdepth 1 \
  -type d -regex '\.\/\..*' 2>/dev/null|wc -l) hidden)"
echo -e "${CMDCOL}Files :${NC} $(find . -maxdepth 1 -type f -regex '\.\/.*' 2>/dev/null|wc -l) ($(find . -maxdepth 1 \
  -type f -regex '\.\/\..*' 2>/dev/null|wc -l) hidden, \
$(ls -1 *.{tgz,tar,a,ar,rpm,iso,bz,bz2,lz,gz,gzip,tar.gzip,rz,7z,s7z,cab,rar,tar.bz2,tar.gz,zz,zip} 2>/dev/null|\
sort -u|wc -l) archived)"
echo -e "${CMDCOL}Links :${NC} $(find . -maxdepth 1 -type l -regex '\.\/.*' 2>/dev/null|wc -l) ($(find . -maxdepth 1 \
  -type l -regex '\.\/\..*' 2>/dev/null|wc -l) hidden)"
echo -e "${CMDCOL}Size  :${NC} $(ls -Agh1 2>/dev/null|head -1|sed 's|total ||') ($(du -h 2>/dev/null|tail -1|\
  sed 's|\s*\.\s*$||') including sub-directories)"
echo
ls --color=auto -Apq
popd 1> /dev/null

