#!/bin/bash
# Copyright (c) 2014 Matt Busby @MrMattBusby
# MIT License (https://github.com/MrMattBusby/bin-tools/blob/master/LICENSE)

PURPOSE="Select a line from a pipe (counts from 0)."
CMDNAME="$0"
USAGE="${CMDNAME} LINE_NO"
HELP="${PURPOSE}\nUsage: \`${USAGE}\`"
BRED='\e[1;31m'
SDARK='\e[2m'
NC='\e[0m'

if [[ "$1" == '-h' ]] ; then
  >&2 echo -e "${HELP}"
	exit 0
elif [ $# -ne 1 ] ; then
  >&2 echo -e "${BRED}${CMDNAME}: error: ${NC}Invalid arguments!\n"
  >&2 echo -e "${SDARK}${HELP}${NC}"
	exit 2
fi

head -$(($1+1)) | tail -1
