#!/bin/bash
PURPOSE="It's (me)! Like whoami but much better; prints information on user/pc/etc."

#   Copyright (c) 2014, Matt Busby @MrMattBusby.
#   All rights reserved.
#
#   Redistribution and use in source and binary forms, with or without
#   modification, are permitted provided that the following conditions
#   are met:
#   
#   1. Redistributions of source code must retain the above copyright
#      notice, this list of conditions and the following disclaimer.
#   
#   2. Redistributions in binary form must reproduce the above copyright
#      notice, this list of conditions and the following disclaimer in
#      the documentation and/or other materials provided with the
#      distribution.
#   
#   3. Neither the name of the copyright holder nor the names of its
#      contributors may be used to endorse or promote products derived
#      from this software without specific prior written permission.
#   
#   THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
#   "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
#   LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
#   FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
#   COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
#   INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
#   BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
#   LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
#   CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
#   LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY
#   WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
#   POSSIBILITY OF SUCH DAMAGE.
#
# TODO:
#  - Use mpstat?


CMDNAME="$0"
USAGE="${CMDNAME}"
HELP="${PURPOSE}\nUsage: \`${USAGE}\`"

BBLACK='\e[1;30m'
BRED='\e[1;31m'
BWHITE='\e[1;37m'
NC='\e[0m'
SDARK='\e[2m'
WHITE='\e[0;37m'

if [[ "$1" == '-h' ]] ; then
  >&2 echo -e "${HELP}"
	exit 0
elif [ $# -ne 0 ] ; then
  >&2 echo -e "${BRED}${CMDNAME}: error: ${NC}Invalid arguments!\n"
  >&2 echo -e "${SDARK}${HELP}${NC}"
	exit 2
fi

IAM=$(if [[ "${USER}" -eq "" ]] ; then whoami ; else echo "${USER}" ; fi)
TTYINFO=$(tty|sed 's|/dev/||')

if command -v uptime &> /dev/null ; then
  HOSTINFO1=$(uptime|grep -o "up.*users" | sed 's|  | |g')
else
  HOSTINFO1='?'
fi

if command -v who &> /dev/null && [[ $(who) -ne "" ]] ; then
  WHOINFO=$(who|grep $USER|grep pts|wc -l)
  HOSTINFO2=$(who -q|head -1|sed 's| |\n|g'|sort -u|xargs)
else
  WHOINFO='?'
  HOSTINFO2='?'
fi

PC_INFO=$(cat /proc/cpuinfo | grep -i "model name" | head -1 | sed 's/.*: //' | xargs)
PC_NUM=$(cat /proc/cpuinfo | grep -i "processor" | wc -l)
AVG=($(cat /proc/loadavg))
if command -v free &> /dev/null ; then
  MEM=($(\free -tm | grep Mem | awk '{print $2,$3}'))
  CACHE=$(\free -tm | grep "\-/+" | awk '{print $3}')
  SWP=($(\free -tm | grep Swap | awk '{print $2,$3}'))
else
  MEM=('?','?')
  CACHE='?'
  SWP=('?','?')
fi

if command -v ipconfig &> /dev/null ; then
  IP=$(ipconfig|egrep -o "IPv4.*[0-9\.]*" | sed "s/.*:\s//g" | xargs | sed 's/ /, /g')
else
  IP=$(/sbin/ifconfig|egrep -o "(inet addr:|inet )[0-9\.]*" | sed "s/inet addr://" | sed "s/inet //" | xargs | sed 's/ /, /g')
fi
OS=$(cat /etc/redhat-release 2>/dev/null || cat /etc/issue 2>/dev/null || uname -s | head -c -1 | sed 's/\\.*//' | sed 's/^\s*//' | sed 's/\s*$//')
UNAME="$(uname -o) $(uname -r)"
VGREP=$(grep --version|head -1|\egrep -o "[0-9]+(\.[0-9]+)+")
#VGNU=$(gnuplot --version|sed 's| patch.*||' | tr ' ' ':')

if command -v gcc &> /dev/null ; then
  VGCC=$(gcc --version|head -1|egrep -o '\(GCC\) .\..\..'|sed 's|(GCC) ||')
else
  VGCC='?'
fi

VVIM=$(vim --version|head -1|egrep -o '.\..')
VSVN=$(svn --version 2>/dev/null|head -1|sed 's|, version||'|sed 's| (.*||' | tr ' ' ':')
VPY=$(echo $(/bin/env python -V 2>&1)|egrep -o "[pP]ython [0-9\.]*" | tr ' ' ':')
DATE=$(date | xargs)

echo -e "${BWHITE}User  ${BBLACK}: ${WHITE}$IAM:$EUID ($HOME)"
echo -e "${BWHITE}Shell ${BBLACK}: ${WHITE}$SHELL $BASHPID ($TERM/$MSYSTEM: $TTYINFO of $WHOINFO)"
echo -e "${BWHITE}Host  ${BBLACK}: ${WHITE}${HOSTNAME} ${DISPLAY} ($HOSTINFO1: $HOSTINFO2)"
echo -e "${BWHITE}PC    ${BBLACK}: ${WHITE}$PC_INFO x$PC_NUM"
echo -e "${BWHITE}Loads ${BBLACK}: ${WHITE}${AVG[@]::4} Mem:${MEM[1]}(${CACHE})/${MEM[0]}Mb Swap:${SWP[1]}/${SWP[0]}Mb"
echo -e "${BWHITE}IPs   ${BBLACK}: ${WHITE}${IP}"
echo -e "${BWHITE}OS    ${BBLACK}: ${WHITE}${OS}: $UNAME"
echo -e "${BWHITE}Vers  ${BBLACK}: ${WHITE}grep:$VGREP gcc:$VGCC VIM:$VVIM $VPY"
echo -e "${BWHITE}Date  ${BBLACK}: ${WHITE}${DATE}${NC}"

