#!/bin/bash
# Copyright (c) 2014-2016, Matt Busby @MrMattBusby.
# MIT License (https://github.com/MrMattBusby/bin-tools/blob/master/LICENSE)

PURPOSE="Find newly modified files."
CMDNAME="$0"
USAGE="${CMDNAME} [LOCATION]"
HELP="${PURPOSE}\nUsage: \`${USAGE}\`"

if [[ "$1" == '-h' ]] ; then
  >&2 echo -e "${HELP}"
	exit 0
fi

find "$@" -type f -printf '%Ty-%Tm-%Td %TH:%TM:%TS %M %u:%g\t%p\n' | sort -n
