#!/bin/bash
# Term color definitions, sourced from .bashrc.
# 
#   Copyright (c) 2014-2015, Matt Busby <busby.gator@gmail.com>.
#   All rights reserved.
#
#   Redistribution and use in source and binary forms, with or without
#   modification, are permitted provided that the following conditions
#   are met:
#   
#   1. Redistributions of source code must retain the above copyright
#      notice, this list of conditions and the following disclaimer.
#   
#   2. Redistributions in binary form must reproduce the above copyright
#      notice, this list of conditions and the following disclaimer in
#      the documentation and/or other materials provided with the
#      distribution.
#   
#   3. Neither the name of the copyright holder nor the names of its
#      contributors may be used to endorse or promote products derived
#      from this software without specific prior written permission.
#   
#   THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
#   "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
#   LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
#   FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
#   COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
#   INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
#   BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
#   LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
#   CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
#   LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY
#   WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
#   POSSIBILITY OF SUCH DAMAGE.

# Normal
export BLACK='\e[0;30m'   # Black
export RED='\e[0;31m'     # Red
export GREEN='\e[0;32m'   # Green
export YELLOW='\e[0;33m'  # Yellow
export BLUE='\e[0;34m'    # Blue
export PURPLE='\e[0;35m'  # Purple
export CYAN='\e[0;36m'    # Cyan
export WHITE='\e[0;37m'   # White

# Bold
export BBLACK='\e[1;30m'  # Black
export BRED='\e[1;31m'    # Red
export BGREEN='\e[1;32m'  # Green
export BYELLOW='\e[1;33m' # Yellow
export BBLUE='\e[1;34m'   # Blue
export BPURPLE='\e[1;35m' # Purple
export BCYAN='\e[1;36m'   # Cyan
export BWHITE='\e[1;37m'  # White

# Dark
export DBLACK='\e[2;30m'  # Black
export DRED='\e[2;31m'    # Red
export DGREEN='\e[2;32m'  # Green
export DYELLOW='\e[2;33m' # Yellow
export DBLUE='\e[2;34m'   # Blue
export DPURPLE='\e[2;35m' # Purple
export DCYAN='\e[2;36m'   # Cyan
export DWHITE='\e[2;37m'  # White

# Light (italics)
export IBLACK='\e[90m'    # Black
export IRED='\e[91m'      # Red
export IGREEN='\e[92m'    # Green
export IYELLOW='\e[93m'   # Yellow
export IBLUE='\e[94m'     # Blue
export IPURPLE='\e[95m'   # Purple
export ICYAN='\e[96m'     # Cyan
export IWHITE='\e[97m'    # White

# Background (highlight)
export HBLACK='\e[40m'    # Black
export HRED='\e[41m'      # Red
export HGREEN='\e[42m'    # Green
export HYELLOW='\e[43m'   # Yellow
export HBLUE='\e[44m'     # Blue
export HPURPLE='\e[45m'   # Purple
export HCYAN='\e[46m'     # Cyan
export HWHITE='\e[47m'    # White

# Light background (highlight)
export LBLACK='\e[100m'   # Black
export LRED='\e[101m'     # Red
export LGREEN='\e[102m'   # Green
export LYELLOW='\e[103m'  # Yellow
export LBLUE='\e[104m'    # Blue
export LPURPLE='\e[105m'  # Purple
export LCYAN='\e[106m'    # Cyan
export LWHITE='\e[107m'   # White

# Special
export SBOLD='\e[1m'
export SDARK='\e[2m'
export SUNDERLINE='\e[4m'
export SINVERT='\e[7m'

# Command color
export CMDCOL=$BCYAN

# No color
export NC='\e[0m'         # Color Reset
