#!/bin/bash
# Copyright (c) 2014 Matt Busby @MrMattBusby
# MIT License (https://github.com/MrMattBusby/bin-tools/blob/master/LICENSE)

PURPOSE="Swap two filenames, fast method, few temp files, confirmation."
CMDNAME="$0"
USAGE="${CMDNAME} FILENAME1 FILENAME2"
HELP="${PURPOSE}\nUsage: \`${USAGE}\`"
BRED='\e[1;31m'
SDARK='\e[2m'
NC='\e[0m'

# Use 2 arguments
if [[ "$1" == '-h' ]] ; then
  >&2 echo -e "${HELP}"
	exit 0
elif [ $# -ne 2 ] ; then
  >&2 echo -e "${BRED}${CMDNAME}: error: ${NC}Invalid arguments!\n"
  >&2 echo -e "${SDARK}${HELP}${NC}"
	exit 2
fi

FILE1=$(dirname $1)/$(basename $1)
FILE2=$(dirname $2)/$(basename $2)

# Check file 1
if [ ! -f $FILE1 -a ! -d $FILE1 ] ; then
	>&2 echo -e "${CMDCOL}swapnames:${NC} file $FILE1 does not exist!"
  exit
fi

# Check file 2
if [ ! -f $FILE2 -a ! -d $FILE2 ] ; then
	>&2 echo -e "${CMDCOL}swapnames:${NC} file $FILE2 does not exist!"
  exit
fi

# Using a temp name w/o copies, swap file names and print confirmation
mv $FILE1 $FILE1.$$ && \
mv $FILE2 $FILE1 && \
mv $FILE1.$$ $FILE2 && \
echo -e "${CMDCOL}swapnames:${NC} swapped filenames \"$FILE1\" with \"$FILE2\"." || \
>&2 echo -e "${CMDCOL}swapnames:${NC} failed!"
