#!/bin/bash
PURPOSE="Swap two filenames, fast method, few temp files, confirmation."
# 
#   Copyright (c) 2014-2016, Matt Busby @MrMattBusby.
#   All rights reserved.
#
#   Redistribution and use in source and binary forms, with or without
#   modification, are permitted provided that the following conditions
#   are met:
#   
#   1. Redistributions of source code must retain the above copyright
#      notice, this list of conditions and the following disclaimer.
#   
#   2. Redistributions in binary form must reproduce the above copyright
#      notice, this list of conditions and the following disclaimer in
#      the documentation and/or other materials provided with the
#      distribution.
#   
#   3. Neither the name of the copyright holder nor the names of its
#      contributors may be used to endorse or promote products derived
#      from this software without specific prior written permission.
#   
#   THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
#   "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
#   LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
#   FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
#   COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
#   INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
#   BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
#   LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
#   CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
#   LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY
#   WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
#   POSSIBILITY OF SUCH DAMAGE.

CMDNAME="$0"
USAGE="${CMDNAME} FILENAME1 FILENAME2"
HELP="${PURPOSE}\nUsage: \`${USAGE}\`"
BRED='\e[1;31m'
SDARK='\e[2m'
NC='\e[0m'

# Use 2 arguments
if [[ "$1" == '-h' ]] ; then
  >&2 echo -e "${HELP}"
	exit 0
elif [ $# -ne 2 ] ; then
  >&2 echo -e "${BRED}${CMDNAME}: error: ${NC}Invalid arguments!\n"
  >&2 echo -e "${SDARK}${HELP}${NC}"
	exit 2
fi

FILE1=$(dirname $1)/$(basename $1)
FILE2=$(dirname $2)/$(basename $2)

# Check file 1
if [ ! -f $FILE1 -a ! -d $FILE1 ] ; then
	>&2 echo -e "${CMDCOL}swapnames:${NC} file $FILE1 does not exist!"
  exit
fi

# Check file 2
if [ ! -f $FILE2 -a ! -d $FILE2 ] ; then
	>&2 echo -e "${CMDCOL}swapnames:${NC} file $FILE2 does not exist!"
  exit
fi

# Using a temp name w/o copies, swap file names and print confirmation
mv $FILE1 $FILE1.$$ && \
mv $FILE2 $FILE1 && \
mv $FILE1.$$ $FILE2 && \
echo -e "${CMDCOL}swapnames:${NC} swapped filenames \"$FILE1\" with \"$FILE2\"." || \
>&2 echo -e "${CMDCOL}swapnames:${NC} failed!"
