#!/usr/bin/env python
# -*- encoding: utf-8 -*-
"""Transpose standard input, for use with Vim

LICENSE

See below __license__

USAGE

`$ echo "1 2 3\n1 2 3" | transpose`
`:'<,'>!transpose`

"""
__creator__ = "Matt Busby"
__email__ = "@MrMattBusby"
__date__ = "2016"

__version__ = "See GitHub"
__project__ = "https://github.com/MrMattBusby/"

__author__ = "{0} {1}".format(__creator__, __email__)
__copyright__ = "Copyright (c) {year}, {owner}. ".format(
                        owner = __author__,
                        year = "2012") + \
                   "All rights reserved."
__licence__ = """\
        BSD 3-Clause License

        {copyright}

        Redistribution and use in source and binary forms, with or without
        modification, are permitted provided that the following conditions
        are met:

        1. Redistributions of source code must retain the above copyright
           notice, this list of conditions and the following disclaimer.

        2. Redistributions in binary form must reproduce the above copyright
           notice, this list of conditions and the following disclaimer in
           the documentation and/or other materials provided with the
           distribution.

        3. Neither the name of the copyright holder nor the names of its
           contributors may be used to endorse or promote products derived
           from this software without specific prior written permission.

        THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
        "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
        LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
        FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
        COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
        INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
        BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
        LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
        CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
        LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY
        WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
        POSSIBILITY OF SUCH DAMAGE.
        """.format(copyright=__copyright__)

import sys

if __name__ == '__main__':
  outs = ''
  for each in zip(*(line.strip().split() for line in sys.stdin.readlines() if line.strip())):
    outs += ' '.join(each) + '\n'
  sys.stdout.write(outs)
