#!/bin/bash
# Copyright (c) 2023 Matt Busby @MrMattBusby
# MIT License (https://github.com/MrMattBusby/bin-tools/blob/master/LICENSE)

/usr/bin/tree $@ 2> /dev/null || find . $@ -print | sed -e 's;[^/]*/;|__;g;s;__|; |;g'
